import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'movie_entity.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'movie_entity.g.dart';

@freezed
abstract class MovieEntity with _$MovieEntity {
  const factory MovieEntity({
    required String title,
    required String year,
    required String bannerUrl,
  }) = _MovieEntity;

  factory MovieEntity.fromJson(Map<String, Object?> json) => _$MovieEntityFromJson(json);
}