import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:netflix_clone/data/api/entity/movie_entity.dart';
import 'package:netflix_clone/shared/exception/api_exception.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'detail_state.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
// part 'detail_state.g.dart';

@freezed
abstract class DetailState with _$DetailState {
  const factory DetailState({
    MovieEntity? movie,
    ApiException? error,
  }) = _DetailState;

  // factory DetailState.fromJson(Map<String, Object?> json) => _$DetailStateFromJson(json);
}